# -*- coding: utf-8 -*-
"""лаб 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBdAy6kfFV5yZlBbb_ZajJrNBhCJYX6Y
"""

i=int(input ())
if i == 1:
    print ("январь")
elif i== 2:
  print("февраль")
elif i== 3:
  print("март")
elif i== 4:
  print("апрель")
elif i== 5:
  print("май")
elif i== 6:
  print("июнь")
elif i== 7:
  print("июль")
elif i== 8:
  print("август")
elif i== 9:
  print("сентябрь")
elif i== 10:
  print("октябрь")
elif i== 11:
  print("ноябрь")
elif i== 12:
  print("декабрь")

i=int(input ())

if i%2== 0:
  print("четное")
elif i%2== 1 :
  print("нечетное")

N= int(input())
if N >= 40 :
    print ("stonks")
elif N <= 40  :
    print (" not stonks")

def is_year_leap(year):
    if year % 4 == 0:
        return True
    else:
        return False

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

def task6(a, b):
    if round(a / b, 1) == 3.6 or pow(-138/2, 1.3) <= b <= abs(pow(-69/28, 5.1) * 4):
        temp = b
        b = a
        a = temp

def task7():
    arr = []
    for i in range(0, 5):
        v = int(input())
        arr.append(v)
    is_unique = True
    even = 0
    negative = 0
    gap = 0
    for item in arr:
        if item % 2 == 0:
            even += 1
        if item < 0:
            negative += 1
        if 256 <= item <= 1024:
            gap += 1
        if arr.count(item) > 1:
            is_unique = False

def task8():
    a = int(input())
    b = int(input())
    c = int(input())
    res = ((pow(a, 2) + pow(b, 3)) / c + 3) / 4
    print(res)
    if res.is_integer():
        if int(res) % 2 == 0:
            print("Четное")
        else:
            print("Нечетное")
    else:
        print("Число дробное")